### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by rtxyd**
Change "core armor" and "lower armor" translations. And there are some personal suggestions for who translate this. 
The reason is below,
I don't think "core armor" should be translated as "高等盔甲" *(high level armor)*,  and the "lower armor" should be translated as "低等盔甲"*(low level armor)*,  If only translate "higher armor" and "lower armor", I would translate as "上身盔甲" *(upper body armor)* and "下身盔甲" *(lower body armor)*. Through my gameplay, the *"core armor"* is *"chestplate"* and *”leggings“*, which should be translated as "核心盔甲"*(core armor)* or "主要盔甲"*(main armor)*, and the *"lower armor"* is *"leggings and boots"*, which should be translted as "下身盔甲"*(lower body armor)*. 
The suggestion is below,
And the "tyrannical gem" should be translated as "暴君宝石" instead of "暴政宝石", though the meaning of Trant and Tranny get different preferance. This is somehow “abstract" if a player see "暴政宝石". The ”暴政“ is a low-frequency expression in casul life, we often talk about this in serious. But I won't change this. Literally, this is correct. As for other translations, I think some of them should be simplified, like "炽热炼狱宝石", just translate as "炽狱宝石", "炽" of "白炽" means *"very high temperature"*, "狱" of "炼狱" means *"inferno"* , 4 characters like older translations of this mod is enough. But this is also personally.
@mc-kaishixiaxue

### CODE REVIEW

**Comment by Shadows-of-Fire** [comment]
I agree with your statements here, in terms of the closest English meaning you can get in translation.

You are correct in that core armor => Chest/Legs and Lower Armor => Legs/Boots.

I can't comment about the Tyrant vs Tyranny statement, as that seems to require contextual nuances that I'm unaware of, but the "very high temperature" vs "inferno" debate should be easily in favor of inferno.

**Comment by mc-kaishixiaxue** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/blob/2c0a757c30551c55e582d8ba930810aaee9f5869/src/main/resources/assets/apotheosis/lang/zh_cn.json#L344-L345
These lines have excess quantifier `个`, in game, the display effect is `number`+`x`+`itemName`, such as `1xGem Dust`.


During the last translation(#821), I found `Exclusive with: *` text cannot be translated. `en_us.json` file doesn't have it. Chinese is `与*互斥`.

**Comment by rtxyd** [comment]
@Shadows-of-Fire  In this commit I only change the armor translation, the suggestion translation is not involved. And this is just for @mc-kaishixiaxue

**Comment by rtxyd** [comment]
@mc-kaishixiaxue 第一个这个可以不用强行翻译，参考以前的翻译文件
https://github.com/Shadows-of-Fire/Apotheosis/blob/dd9c50dbdf4a1304fe7d65d5783b9b07a2bdc8ab/src/main/resources/assets/apotheosis/lang/zh_cn.json#L288-L289
第二个可以使用
`"Exclusive With: %s" : "与%s冲突" ` 翻译
参考源代码
https://github.com/Shadows-of-Fire/Apotheosis/blob/dd9c50dbdf4a1304fe7d65d5783b9b07a2bdc8ab/src/main/java/shadows/apotheosis/ench/table/EnchantingInfoScreen.java#L165

**Comment by rtxyd** [comment]
> but the "very high temperature" vs "inferno" debate should be easily in favor of inferno.

Actually, "炽热炼狱宝石"*(gem of very high temperature inferno)* is a direct translation of original words "Gem of Incandescent Inferno", and "白炽" or "炽热" is the direct translation of *"Incandescent"*, "炼狱" is the direct translation of *"Inferno"*. 
I personally prefer extract key words of "炽热" to "炽", "炼狱" to "狱", and combine into "炽狱", it's the same meaning, but short and accurate.

**Pull request merged**
