### PR TITLE
zh_cn translation fix

### PR DESCRIPTION
**Pull request by rtxyd**
Based on previous translation by @mc-kaishixiaxue and the en_us.json and my gameplay, I found them with manny grammar mistakes and wrong translations that make me hard to read. So made this fix today.

What I change  for example:

- About terms of game like `percentage modifier` and `flat modifier` in attributes description,

because they are used on context so I regard this as they are diffirent aspects of a damage modifier, it may be referring to `*"multiplicative modifier"*` or `*"addictive modifier"*`, but I am affraid the `*"percentage modifier"*` comes up here may not be same meaning as my understanding, so this need a check. If not so, I will change to really meaning.

https://github.com/Shadows-of-Fire/Apotheosis/blob/8dd0e82e1c091555748b648e0f36063b3fde8687/src/main/resources/data/apotheosis/patchouli_books/apoth_chronicle/en_us/entries/adventure/attributes/crit_chance.json#L14

 & [reference article: what is flat damage](https://www.reddit.com/r/NoStupidQuestions/comments/qng05w/what_is_a_flat_modifier/)

-  And On-hit damage, if my opinion is right, this is like a *"attack effects"* of LOL, so I just translate it into "攻击特效伤害"`(attack effects damage)` rather "命中伤害"(hit damage) 

& [reference article: on-hit-effects](https://leaguefeed.net/on-hit-effects/)

https://github.com/Shadows-of-Fire/Apotheosis/blob/8dd0e82e1c091555748b648e0f36063b3fde8687/src/main/resources/data/apotheosis/patchouli_books/apoth_chronicle/zh_cn/entries/adventure/attributes/current_hp_damage.json#L10

- About sentences IDK what they are expressing,

previous:
https://github.com/Shadows-of-Fire/Apotheosis/blob/8dd0e82e1c091555748b648e0f36063b3fde8687/src/main/resources/data/apotheosis/patchouli_books/apoth_chronicle/zh_cn/entries/enchanting/table/info.json#L37

original:
https://github.com/Shadows-of-Fire/Apotheosis/blob/8dd0e82e1c091555748b648e0f36063b3fde8687/src/main/resources/data/apotheosis/patchouli_books/apoth_chronicle/en_us/entries/enchanting/table/info.json#L37

I think this text is saying `"if you match all these two condition (give an item, select a power level) to enchantment table a certain list of enchantments may occur"`. It's somehow not willing to read previous translation for me.

- About not  correctly point oringinal meaning,

In this case, the previous translation don't involved  `"in the middle of"` key words, the slider will be in the middle on start from my gameplay. So I translate this as “The Power slider is automatically set directly to the center of the Power range”.
previous tranlation:
https://github.com/Shadows-of-Fire/Apotheosis/blob/8dd0e82e1c091555748b648e0f36063b3fde8687/src/main/resources/data/apotheosis/patchouli_books/apoth_chronicle/zh_cn/entries/enchanting/table/info.json#L49

original:
https://github.com/Shadows-of-Fire/Apotheosis/blob/8dd0e82e1c091555748b648e0f36063b3fde8687/src/main/resources/data/apotheosis/patchouli_books/apoth_chronicle/en_us/entries/enchanting/table/info.json#L49

- Another case about wrong translation.

previous tranlation:
https://github.com/Shadows-of-Fire/Apotheosis/blob/8dd0e82e1c091555748b648e0f36063b3fde8687/src/main/resources/data/apotheosis/patchouli_books/apoth_chronicle/zh_cn/entries/adventure/affix_loot/reforging.json#L46
original:
https://github.com/Shadows-of-Fire/Apotheosis/blob/8dd0e82e1c091555748b648e0f36063b3fde8687/src/main/resources/data/apotheosis/patchouli_books/apoth_chronicle/en_us/entries/adventure/affix_loot/reforging.json#L46
in this case, the `"Items can be reforged multiple times, but you must pick up and replace the item first."` in which the `"replace"` could be replaced as `"re-place".` , so there should be translated as "重新放回"`(place again)` rather "替换"`(replace of)`

- Translate with wrong syntactic, 

Not like a Chinese syntactic. 
previous:
https://github.com/Shadows-of-Fire/Apotheosis/blob/8dd0e82e1c091555748b648e0f36063b3fde8687/src/main/resources/data/apotheosis/patchouli_books/apoth_chronicle/zh_cn/entries/enchanting/table/stats.json#L20
original:
https://github.com/Shadows-of-Fire/Apotheosis/blob/8dd0e82e1c091555748b648e0f36063b3fde8687/src/main/resources/data/apotheosis/patchouli_books/apoth_chronicle/en_us/entries/enchanting/table/stats.json#L20
 This should be translated as "quanta is a secondary stat `(the important rank)`, (it) controls enchanting variance `(the higher or lower power it may grant)`. during enchanting you have a base power = the level you spend and a after-being-modified final power", in Chinese translation there shouldn't be too much inaccurate postponement of the adverbrial sentences.
And this translation is also missing the last sentence of the text. `$(p)$(quanta) is one of the factors in the modification process.`

- Some small tweaks to make the sentences more readable such as add subject/predicate/object to a known word.

Like
 `power`. For there may have a certain subject for power to make it more readable, so I chose to translate as "附魔威力"`("enchanting power")` rather simple 威力`"power"`.

https://github.com/Shadows-of-Fire/Apotheosis/blob/8dd0e82e1c091555748b648e0f36063b3fde8687/src/main/resources/data/apotheosis/patchouli_books/apoth_chronicle/en_us/entries/enchanting/table/power.json#L2

`"Stats"` translated as "attributes" for if translated into "状态"`(status)` not correct, it should be the short form of `"statistics"`. In my opinion the `"attributes"` or `"certain values of abilities"` of an enchantment table are `"statistics"` of it.

[refering to: how enchantment works ](http://pernsteiner.org/minecraft/enchant/algo.html)

### CODE REVIEW

**Comment by mc-kaishixiaxue** [comment]
https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/resources/data/apotheosis/patchouli_books/apoth_chronicle/zh_cn/entries/potion/recipes/fatigue.json#L10

远古守卫者者->远古守卫者

**Comment by rtxyd** [comment]
found a new issue in this file, working on it.

https://github.com/rtxyd/Apotheosis/blob/c0b87c2a39b3d8c7b692d9bc1615c7145a544fdb/src/main/resources/data/apotheosis/patchouli_books/apoth_chronicle/zh_cn/entries/enchanting/table/infusion.json#L13

**Comment by rtxyd** [comment]
Have a peek of zh_cn.lang, I really need to tweak some translations to make it better.

**Comment by rtxyd** [comment]
OK, basicly done, 
About why I tweak zh_cn.lang:
for example,

1. "legacy gem" should not be "远古宝石" `(ancient gem)` should be translated as "经典宝石"`(classic gem)` for they work for previous version.
2. "ballast gem" --> "压载宝石"`(ballast gem)` --> "稳定宝石"`(stablizier gem)` previous translation is a term that may not directly express the meaning of name. So I tranlate it into which you can easily get the meaning of name.
3. "solar gem" --> "太阳宝石"`(solar gem)` -->"阳炎宝石"`(gem of solar flame)` for the gem provides flame damage and the better pronunciation and meaning.
4. "lunar gem" --> "月亮宝石"`(lunar gem)`,-->"月华宝石"`(gem of moonlight)` as the gem provide cold damage, I translate it into this for the better pronunciation and meaning.
5. "gem of warlord" --> "军阀宝石"`(warlord gem)` --> "战神宝石"`(warlord gem)` ,"军阀" appears here which is somehow not such suitable, and in game, the gem provides crit chance and total damage modifier, so I do,
6. As for "tyrannical gem" --> "暴政宝石" -->"暴君宝石"(tyrant gem), it's not suitable either, and in game it provide crit damage so I do.
7. "breach" should not be "破坏宝石"`(breaking gem)`, I see it seems mostly like a limit breaker for attributes rather a simple gem for breaking. So I just use "突破宝石"`(limit breaker gem)`

And I make every name of gem 4 Chinese characters for neat.

**Comment by Shadows-of-Fire** [comment]
The names of the gems are sort of arbitrary, so I wouldn't stress too much about correctness on those

**Comment by rtxyd** [comment]
For better gameplay, the more rare or powerful the item is, should be translated more carefully. just directly translate them can't make them integrated with the whole things the mod bring. I used to make machine translation and I learn a lesson of it.

**Comment by Shadows-of-Fire** [comment]
cc @Aikini for visibility

**Pull request merged**
