### PR TITLE
Early affixes port

### PR DESCRIPTION
**Pull request by procrastinator3000**
Minecraft modding noob had some spare time so he decided to level up his coding skills and get deadly module running in 1.18.2 (want to play with friend for a bit :) ). 

Whats done:
-re-added affix/rarity shards, affix tomes (with cooking/crafting recipes). 
-surface bosses spawns. 
-affix items from random mobs. 
-most of affixes from 1.16 (had issues with some, see comments in code). 
-changed bits in PL translation to less vulgar / more correct in given context

Whats missing:
-worldgen stuff (no tome towers/rogue spawners etc) (started working on it)
-affix modifiers (modifiers to affix value ranges depending on item rarity)

I plan to code missing stuff this week. Would love to know if you have any ideas for implementation/rewrite of affix parts. AttributeAffix with its builder looks like some attempt but I dont think its going to work for other affixes (and actually causes issues for some AttributeAffixes like fire damage?). Beyond missing things listed Im willing/interested to help develop mod for a bit if there are any extra ideas I can help with :) 

Cheers,
pc3k

PS. Changes were briefly tested and Ive observed no crashes or weird names

### CODE REVIEW

**Comment by Shadows-of-Fire** [comment]
This is neat™
I'll let this sit here in case I feel like referencing it, though chances of a merge happening are pretty much 0%, since I will be rewriting this system from scratch to be better-designed.

**Comment by procrastinator3000** [comment]
Rewrite in this case sounds like great idea. I was tempted to write a common config/props class for affixes and load them with DataGenerator/JsonReloadListener but decided to make things at least work as they were before I go down the rabit hole. Any loose estimate when rewrite can be expected? I have few ideas for affixes/features I want to implement for myself and if thats not too far away I would just wait and steal solution :) I would prefer to keep compatibility with this repo because im playing minecraft every now and then with lenghty breaks. In case of minecraft/forge update in the mean time there is a chance someone would do porting here.

**Comment by Shadows-of-Fire** [comment]
It is fairly far away, it's blocked on some forge PR's which are blocked in waiting for a response from mojang on some vanilla bugs.

**Comment by procrastinator3000** [comment]
I guess then I will try write something half decent as temporary (read: write and use 4ever) solution after Im done with worldgen stuff. Hope it will come handy later. I will make it public on fork for sure so if anything, feel free to make use of it. Cheers

**Comment by Midlex** [comment]
Is there any way to download this pr as compiled .jar? or is it better to wait for update?

**Comment by procrastinator3000** [comment]
As @Shadows-of-Fire had said, update to affixes is 'fairly far away'. If you dont mind alpha versions then there is compiled release on fork : [5.4.1A](https://github.com/procrastinator3000/Apotheosis/releases/tag/5.4.1A). It contains changes from this PR + some other stuff I have managed to add in the mean time, see release notes to know whats up. I am currently working on my take of affixes rewrite and expect to finish soon (week or so). Any fixes to broken affixes will come after that. If you happen to get any crash or broken behaviour related to changes I've made you can let me know via Issues on fork and I'll try to help as soon as I can. 

Also, question to @Shadows-of-Fire . Should I add some prefix to jar name to make it easily identifiable that it's from fork so users will not blame you for bugs introduced by me? Or you are totally fine having some angry users with pitchforks coming at you from time to time :D

**Comment by Shadows-of-Fire** [comment]
Probably best to affix the version string with something.

**Comment by Midlex** [comment]
> As @Shadows-of-Fire had said, update to affixes is 'fairly far away'. If you dont mind alpha versions then there is compiled release on fork : [5.4.1A](https://github.com/procrastinator3000/Apotheosis/releases/tag/5.4.1A). It contains changes from this PR + some other stuff I have managed to add in the mean time, see release notes to know whats up. I am currently working on my take of affixes rewrite and expect to finish soon (week or so). Any fixes to broken affixes will come after that. If you happen to get any crash or broken behaviour related to changes I've made you can let me know via Issues on fork and I'll try to help as soon as I can.
> 
> Also, question to @Shadows-of-Fire . Should I add some prefix to jar name to make it easily identifiable that it's from fork so users will not blame you for bugs introduced by me? Or you are totally fine having some angry users with pitchforks coming at you from time to time :D

Thanks really looking forward for this mod

**Pull request closed without merging**
