### PR TITLE
Slight changes to the Brazilian Portugese translations

### PR DESCRIPTION
**Pull request by PedroF9**
Changed 'geradores' back to 'spawners' as it is usually not translated and sounds a bit off when it is.
 Added translation to the description and info about the 'Altar of the seas'.

### CODE REVIEW

**Comment by Shadows-of-Fire** [comment]
cc: @t0piy as the original author

**Comment by PedroF9** [comment]
sorry about that :P

**Comment by Shadows-of-Fire** [comment]
It's not really a credit thing, I just try to pull in previous lang authors for comment on changes to the file
Usually they don't respond, lol

**Comment by PedroF9** [comment]
ah, I see

**Comment by t0piy** [comment]
I translated "Spawners" as "Geradores" because that's how it is translated into Brazilian Portuguese in the Java version of Minecraft (The word "Spawner" and neither its plural is mentioned in PT-BR). Also I didn't translate the Altar of the Sea related stuff because the content is no longer present in the mod

**Comment by PedroF9** [comment]
Thank you for taking the time to explain it to me. I'm just doing a project that requires translation and thought that the altar of the seas was something that was still in the mod. As for the rest of the explanation I will keep that in mind when doing future works. Much appreciated.

**Comment by t0piy** [comment]
> Thank you for taking the time to explain it to me. I'm just doing a project that requires translation and thought that the altar of the seas was something that was still in the mod. As for the rest of the explanation I will keep that in mind when doing future works. Much appreciated.

Always glad to help! 

A tip that can help with the translation: in the official PT-BR translation of Minecraft Java Edition, the name of the items has only the first word starting with a capital letter.  In Brazilian Portuguese language, it is up to the author whether he wants only the first word starting with a capital letter or the whole sentence, which is a little different from what happens with EN-US. Basically it is more interesting that you translate "Gerador de porco lendário" than "Gerador de Porco Lendário", because that way the translation is more reliable in relation to Minecraft Java Edition

**Pull request closed without merging**
